package twilio.lib.twiml;

/**
	This code was generated by
	\ / _    _  _|   _  _
	  | (_)\/(_)(_|\/| |(/_  v1.0.0
	       /       /
**/
@:jsRequire("twilio/lib/twiml/FaxResponse") extern class FaxResponse {
	/**
		<Response> TwiML for Faxes
	**/
	function new();
	/**
		<Receive> TwiML Verb
	**/
	function receive(?attributes:twilio.lib.twiml.faxresponse.ReceiveAttributes):Void;
	/**
		Convert to XML
	**/
	function toString():String;
	static var prototype : FaxResponse;
}