package twilio.lib.twiml;

/**
	This code was generated by
	\ / _    _  _|   _  _
	  | (_)\/(_)(_|\/| |(/_  v1.0.0
	       /       /
**/
@:jsRequire("twilio/lib/twiml/VoiceResponse") extern class VoiceResponse {
	/**
		<Response> TwiML for Voice
	**/
	function new();
	/**
		<Connect> TwiML Verb
	**/
	function connect(?attributes:twilio.lib.twiml.voiceresponse.ConnectAttributes):twilio.lib.twiml.voiceresponse.Connect;
	/**
		<Dial> TwiML Verb
		
		<Dial> TwiML Verb
	**/
	@:overload(function(?attributes:twilio.lib.twiml.voiceresponse.DialAttributes, ?number:String):twilio.lib.twiml.voiceresponse.Dial { })
	function dial(?number:String):twilio.lib.twiml.voiceresponse.Dial;
	/**
		<Echo> TwiML Verb
	**/
	function echo(?attributes:Dynamic):Void;
	/**
		<Enqueue> TwiML Noun
		
		<Enqueue> TwiML Noun
	**/
	@:overload(function(?attributes:twilio.lib.twiml.voiceresponse.EnqueueAttributes, ?name:String):twilio.lib.twiml.voiceresponse.Enqueue { })
	function enqueue(?name:String):twilio.lib.twiml.voiceresponse.Enqueue;
	/**
		<Gather> TwiML Verb
	**/
	function gather(?attributes:twilio.lib.twiml.voiceresponse.GatherAttributes):twilio.lib.twiml.voiceresponse.Gather;
	/**
		<Hangup> TwiML Verb
	**/
	function hangup(?attributes:Dynamic):Void;
	/**
		<Leave> TwiML Verb
	**/
	function leave(?attributes:Dynamic):Void;
	/**
		<Pause> TwiML Verb
	**/
	function pause(?attributes:twilio.lib.twiml.voiceresponse.PauseAttributes):Void;
	/**
		<Pay> Twiml Verb
	**/
	function pay(?attributes:twilio.lib.twiml.voiceresponse.PayAttributes):twilio.lib.twiml.voiceresponse.Pay;
	/**
		<Play> TwiML Verb
		
		<Play> TwiML Verb
	**/
	@:overload(function(?attributes:twilio.lib.twiml.voiceresponse.PlayAttributes, ?url:String):Void { })
	function play(?url:String):Void;
	/**
		<Prompt> Twiml Verb
	**/
	function prompt(?attributes:twilio.lib.twiml.voiceresponse.PromptAttributes):twilio.lib.twiml.voiceresponse.Prompt;
	/**
		<Queue> TwiML Noun
		
		<Queue> TwiML Noun
	**/
	@:overload(function(attributes:twilio.lib.twiml.voiceresponse.QueueAttributes, name:String):Void { })
	function queue(name:String):Void;
	/**
		<Record> TwiML Verb
	**/
	function record(?attributes:twilio.lib.twiml.voiceresponse.RecordAttributes):Void;
	/**
		<Redirect> TwiML Verb
		
		<Redirect> TwiML Verb
	**/
	@:overload(function(attributes:twilio.lib.twiml.voiceresponse.RedirectAttributes, url:String):Void { })
	function redirect(url:String):Void;
	/**
		<Refer> TwiML Verb
	**/
	function refer(?attributes:twilio.lib.twiml.voiceresponse.ReferAttributes):twilio.lib.twiml.voiceresponse.Refer;
	/**
		<Reject> TwiML Verb
	**/
	function reject(?attributes:twilio.lib.twiml.voiceresponse.RejectAttributes):Void;
	/**
		<Say> TwiML Verb
		
		<Say> TwiML Verb
	**/
	@:overload(function(attributes:twilio.lib.twiml.voiceresponse.SayAttributes, message:String):twilio.lib.twiml.voiceresponse.Say { })
	function say(message:String):twilio.lib.twiml.voiceresponse.Say;
	/**
		<Sms> TwiML Noun
		
		<Sms> TwiML Noun
	**/
	@:overload(function(attributes:twilio.lib.twiml.voiceresponse.SmsAttributes, message:String):Void { })
	function sms(message:String):Void;
	/**
		<Start> TwiML Verb
	**/
	function start(?attributes:twilio.lib.twiml.voiceresponse.StartAttributes):twilio.lib.twiml.voiceresponse.Start;
	/**
		<Stop> TwiML Verb
	**/
	function stop(?attributes:Dynamic):twilio.lib.twiml.voiceresponse.Stop;
	/**
		Convert to XML
	**/
	function toString():String;
	static var prototype : VoiceResponse;
}