package twilio.lib.rest.preview.hosted_numbers.hostednumberorder;

typedef HostedNumberOrderStatus = twilio.lib.rest.preview.hosted_numbers.authorizationdocument.dependenthostednumberorder.DependentHostedNumberOrderStatus;